database:
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:{DIR}{NAME}.db
  username: root
  password: ''
  isolation: SERIALIZABLE
  logging: false
  rebuild: false
PointOfInterest:
  defaultPrice: 300.0
  markersetName: LocalPlanPOI
  markerMaximumDistance: 1000.0
